project_id = "fsvfbnzbupchndgtsqun"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = true
enable_phone_confirmations = false
enable_phone_change_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template = { invite = "", confirmation = "", recovery = "", magic_link = "", email_change = "" }

[auth.sms]
enable_signup = false
enable_confirmations = false
template = ""

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.figma]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[edge_runtime]
enabled = true
ip_version = "ipv4"
port = 54330
inspector_port = 8083

[functions.ai-extract-expense]
verify_jwt = false