// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsvfbnzbupchndgtsqun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzdmZibnpidXBjaG5kZ3RzcXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDgxNzQsImV4cCI6MjA3Mjk4NDE3NH0.JAI8nt9qwr7ZJ0etd0QVHxWYI1X6lVm6lqQDjFvj8Ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});